#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wslu
Version  : 4.0.0
Release  : 1
URL      : https://github.com/wslutilities/wslu/archive/refs/tags/v4.0.0.tar.gz
Source0  : https://github.com/wslutilities/wslu/archive/refs/tags/v4.0.0.tar.gz
Summary  : A collection of utilities for the Linux Subsystem for Windows
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0-or-later
Requires: wslu-bin = %{version}-%{release}
Requires: wslu-data = %{version}-%{release}
Requires: wslu-license = %{version}-%{release}
Requires: wslu-man = %{version}-%{release}

%description
This is a collection of utilities for Windows 10 Linux Subsystem, such as converting WSL path to Windows path or creating your favorite linux app shortcuts on Windows 10 Desktop. Requires Windows 10 Creators Update and higher.

%package bin
Summary: bin components for the wslu package.
Group: Binaries
Requires: wslu-data = %{version}-%{release}
Requires: wslu-license = %{version}-%{release}

%description bin
bin components for the wslu package.


%package data
Summary: data components for the wslu package.
Group: Data

%description data
data components for the wslu package.


%package license
Summary: license components for the wslu package.
Group: Default

%description license
license components for the wslu package.


%package man
Summary: man components for the wslu package.
Group: Default

%description man
man components for the wslu package.


%prep
%setup -q -n wslu-4.0.0
cd %{_builddir}/wslu-4.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1661793556
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1661793556
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/wslu
cp %{_builddir}/wslu-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/wslu/31a3d460bb3c7d98845187c716a30db81c44b615
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wslact
/usr/bin/wslclip
/usr/bin/wslfetch
/usr/bin/wslgsu
/usr/bin/wslsys
/usr/bin/wslupath
/usr/bin/wslusc
/usr/bin/wslvar
/usr/bin/wslview

%files data
%defattr(-,root,root,-)
/usr/share/wslu/conf
/usr/share/wslu/get_dpi.ps1
/usr/share/wslu/runHidden.vbs
/usr/share/wslu/sudo.ps1
/usr/share/wslu/wsl-gui.ico
/usr/share/wslu/wsl-term.ico
/usr/share/wslu/wsl.ico
/usr/share/wslu/wslusc-helper.sh
/usr/share/wslu/wslview.desktop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/wslu/31a3d460bb3c7d98845187c716a30db81c44b615

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/wslact.1.gz
/usr/share/man/man1/wslclip.1.gz
/usr/share/man/man1/wslfetch.1.gz
/usr/share/man/man1/wslgsu.1.gz
/usr/share/man/man1/wslsys.1.gz
/usr/share/man/man1/wslupath.1.gz
/usr/share/man/man1/wslusc.1.gz
/usr/share/man/man1/wslvar.1.gz
/usr/share/man/man1/wslview.1.gz
/usr/share/man/man7/wslu.7.gz
